import { Restaurant } from '@/components/comp/RestaurantListing';

export const restaurantsColombo = [
  {
    id: 1,
    name: 'Shanmugas',
    image: '/restaurant.jpg',
    slogan: 'Where Flavor Meets Tradition, Purely Vegetarian',
  },
  {
    id: 2,
    name: 'The Bayleaf',
    image: '/restaurant2.jpg',
    slogan: 'A Taste of Elegance, A Hint of Spice',
  },
  {
    id: 3,
    name: 'The Gallery Cafe',
    image: '/restaurant3.avif',
    slogan: 'Savor the Essence of Fine Dining',
  },
  {
    id: 4,
    name: 'Palmyrah Restaurant',
    image: '/restaurant4.avif',
    slogan: 'Where Every Meal is an Experience',
  },
  {
    id: 5,
    name: "Cuisine Colombo - Gregory's Road",
    image: '/restaurant5.avif',
    slogan: 'A Journey Through Flavor',
  },
  {
    id: 6,
    name: 'Shang Palace',
    image: '/restaurant6.avif',
    slogan: 'Where Modern Meets Comfort',
  },

  {
    id: 7,
    name: 'Arabian Knights',
    image: '/restaurant3.jpg',
    slogan: 'Experience the Magic of Arabian Nights',
  },
  {
    id: 8,
    name: 'Hadaramout Restaurant',
    image: '/restaurant7.avif',
    slogan: 'Taste the Tradition, Savor the Memories',
  },
];

export const cities = [
  { name: 'Colombo', image: '/colombo.jpg' },
  { name: 'Gampaha', image: '/gampaha.png' },
  { name: 'Kalutara', image: '/kalutara.webp' },
  { name: 'Galle', image: '/galle.jpg' },
  { name: 'Kandy', image: '/kandy.jpg' },
  // { name: 'Kalutara', image: '/kalutara.webp' },
  { name: 'Anuradhapura', image: '/anuradhapura.webp' },
  { name: 'Ampara', image: '/Ampara.jpg' },
  { name: 'Badulla', image: '/badulla.jpg' },
  { name: 'Batticaloa', image: '/batticaloa.jpg' },
  // { name: 'Dambulla', image: '/dambulla.jpg' },
  // { name: "Colombo", image: "/colombo.jpg" },
  // { name: 'Gampaha', image: '/gampaha.png' },

  // { name: 'Galle', image: '/galle.jpg' },
  { name: 'Hambantota', image: '/hammantota.jpg' },
  { name: 'Jaffna', image: '/jaffna.webp' },

  { name: 'Kegalle', image: '/kegalle.jpg' },
  { name: 'Kilinochchi', image: '/kilinochchi.jpg' },
  { name: 'Kurunegala', image: '/kurunegala.jpg' },
  { name: 'Mannar', image: '/mannar.jpg' },
  { name: 'Matara', image: '/matara.jpg' },
  { name: 'Matale', image: '/matale.jpg' },
  { name: 'Monaragala', image: '/monaragala.jpg' },
  { name: 'Mullaitivu', image: '/mullaitivu.jpg' },
  { name: 'Nuwara Eliya', image: '/nuwaraeliya.webp' },
  { name: 'Polonnaruwa', image: '/polonnaruwa.webp' },
  { name: 'Puttalam', image: '/puttalam.jpg' },
  { name: 'Ratnapura', image: '/ratnapura.jpg' },
  { name: 'Trincomalee', image: '/trinco.jpg' },
  { name: 'Vavuniya', image: '/vavuniya.jpg' },
];

export const reservations = [
  {
    id: 1,
    tableNumber: 3,
    date: '21.05.2024',
    startTime: '09:40',
    endTime: '10:20',
    guestCount: 1,
  },
  {
    id: 2,
    tableNumber: 5,
    date: '21.05.2024',
    startTime: '11:00',
    endTime: '11:15',
    guestCount: 1,
  },
  {
    id: 3,
    tableNumber: 1,
    date: '21.05.2024',
    startTime: '11:30',
    endTime: '12:45',
    guestCount: 1,
  },
  {
    id: 4,
    tableNumber: 7,
    date: '21.05.2024',
    startTime: '15:00',
    endTime: '16:00',
    guestCount: 1,
  },
  {
    id: 5,
    tableNumber: 2,
    date: '21.05.2024',
    startTime: '16:00',
    endTime: '18:00',
    guestCount: 1,
  },
  {
    id: 6,
    tableNumber: 3,
    date: '21.05.2024',
    startTime: '18:10',
    endTime: '18:40',
    guestCount: 1,
  },
  {
    id: 7,
    tableNumber: 5,
    date: '21.05.2024',
    startTime: '18:50',
    endTime: '19:00',
    guestCount: 1,
  },
  {
    id: 8,
    tableNumber: 1,
    date: '21.05.2024',
    startTime: '19:00',
    endTime: '19:20',
    guestCount: 1,
  },
  {
    id: 9,
    tableNumber: 4,
    date: '21.05.2024',
    startTime: '20:40',
    endTime: '20:50',
    guestCount: 1,
  },
  {
    id: 10,
    tableNumber: 6,
    date: '21.05.2024',
    startTime: '21:00',
    endTime: '21:15',
    guestCount: 1,
  },
];
